import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import "./globals.css";
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] });



export const metadata: Metadata = {
  title: "First WebContainer Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' ' + GeistMono.variable}>
        <Toaster
          position="bottom-center"
          expand={true}
          richColors
        />
        {children}
      </body>
    </html>
  );
}
